paginate: 2
pygments: true
safe: true
published: false
include: [/tags]
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"