FROM node:24-alpine AS builder

# 1. 配置 apk 换源 (阿里云) + 安装 Git
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories && \
    apk add --no-cache git

# 2. 配置 Corepack 环境变量（镜像源 + 禁用下载交互确认提示）
ENV COREPACK_NPM_REGISTRY=https://registry.npmmirror.com
ENV COREPACK_ENABLE_DOWNLOAD_PROMPT=0

# 3. 启用 Corepack 并初始化 pnpm
RUN corepack enable && corepack prepare pnpm@latest --activate \
    && pnpm config set registry https://registry.npmmirror.com \
    && pnpm config set fetch-timeout 600000